---
- name: Create AdGuard Home directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - '{{ adguardhome_home }}/work'
    - '{{ adguardhome_home }}/conf'
    - '/etc/systemd/resolved.conf.d'

- name: Apply systemd-resolved config file
  ansible.builtin.copy:
    src: adguardhome.conf
    dest: /etc/systemd/resolved.conf.d/adguardhome.conf
    owner: root
    group: root
    mode: 0644
  register: _resolved_config

- name: Update /etc/resolv.conf symlink
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
  when: _resolved_config.changed | default(false)
  tags: skip_ansible_lint
