---
- name: Create AdGuard Home directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - '{{ adguardhome_home }}/work'
    - '{{ adguardhome_home }}/conf'
