---
- name: Create AdGuard Home directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - '{{ adguardhome_home }}/work'
    - '{{ adguardhome_home }}/conf'
    - '/etc/systemd/resolved.conf.d'

- when: ansible_service_mgr == 'systemd'
  block:
  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Disable systemd-resolved DNSStubListener
    ansible.builtin.include_tasks: resolved.yml
    when:
      - ansible_facts.services['systemd-resolved.service'] is defined
      - ansible_facts.services['systemd-resolved.service'].status == 'enabled'
