categories:
  - title: 'Roles Changes'
    label: 'roles'  #9126A2
  - title: 'Plugins Changes'
    label: 'plugins'  #A74EBB
  - title: 'CI Changes'
    label: 'ci'
  - title: 'Deprecations'
    label: 'deprecated'  #CFD3D7
exclude-labels:
  - 'skip-changelog'
template: |
  $CHANGES
