categories:
  - title: 'Roles Changes'
    label: 'roles'  #9126A2
  - title: 'Plugins Changes'
    label: 'plugins'  #A74EBB
  - title: 'Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Continuous Integration'
    label: 'ci'  #0E8A16
  - title: 'Deprecations'
    label: 'deprecated'  #CFD3D7
exclude-labels:
  - 'skip-changelog'
template: |
  $CHANGES
