---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Install PowerShell snap
      community.general.snap:
        name: powershell
        classic: true

    - name: Run PowerShell snap
      ansible.builtin.command: pwsh --version
      register: pwsh

    - name: Verify command output
      ansible.builtin.assert:
        that: "'PowerShell' in pwsh.stdout"
