---
namespace: bonddim
name: linux
description: Linux roles collection for different purposes
version: 1.3.1
authors:
  - Dmytro Bondar

readme: README.md
repository: https://github.com/bonddim/ansible-collection-linux
issues: https://github.com/bonddim/ansible-collection-linux/issues
documentation: https://github.com/bonddim/ansible-collection-linux/blob/main/README.md
homepage: https://github.com/bonddim/ansible-collection-linux
license_file: LICENSE
license: []

dependencies:
  community.general: '>=1.0.0,!=3.3.0,!=3.3.1'
  community.docker: '>=1.0.0'

tags:
  - linux
  - system
  - development
  - networking
  - packaging
  - web
  - virtualization

build_ignore:
  - .ansible-lint
  - .cache
  - .github
  - .gitignore
  - .yamllint
  - molecule
  - requirements.txt
