---
dependencies:
  - role: bonddim.linux.snapd
    snap_packages:
      - lxd

galaxy_info:
  description: Install LXD daemon from Snapcraft. Migrate legacy LXD on Ubuntu < 20.04
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags: []
