---
dependency:
  name: galaxy
  enabled: false
driver:
  name: lxd
lint: |
  set -e
  ansible-lint "roles/${MOLECULE_SCENARIO_NAME}"
platforms:
  - name: instance
    url: "${LXD_HOST:-unix:/var/snap/lxd/common/lxd/unix.socket}"
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"
provisioner:
  name: ansible
  connection_options:
    ansible_lxd_remote: "${LXD_REMOTE:-local}"
verifier:
  name: ansible
