---
- name: Converge
  hosts: all
  gather_facts: false
  roles:
    - role: bonddim.linux.users
      managed_users:
        - name: ansible
          system: true
          home: /etc/ansible
          create_home: false
