---
# defaults file for adguard role
# Common vars
adguardhome_home: /opt/adguardhome
adguardhome_version: latest
adguardhome_install_method: docker  # possible values docker, snap
adguardhome_listen_all: true

# Docker related vars
adguardhome_docker_image: adguard/adguardhome
adguardhome_docker_hosts:
  - ['{{ ansible_fqdn }}', '{{ ansible_default_ipv4.address }}']
adguardhome_docker_labels: {}
adguardhome_docker_mounts:
  - '{{ adguardhome_home }}/conf:/opt/adguardhome/conf'
  - '{{ adguardhome_home }}/work:/opt/adguardhome/work'
adguardhome_docker_network: bridge
adguardhome_docker_ports:
  - 53:53/tcp
  - 53:53/udp
  - 3000:3000/tcp

# Snap related vars
adguardhome_snap_channel: latest/stable
