---
name: default

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    paths-ignore:
      - 'roles/**'
      - 'molecule/**'
      - '.github/**'
      - '!.github/workflows/default.yaml'

env:
  NAMESPACE: bonddim
  COLLECTION: linux

jobs:
  sanity:  # https://docs.ansible.com/ansible/latest/dev_guide/testing_sanity.html
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install ansible-base
      - run: ansible-test sanity --docker -v --color
