---
name: '!gh-pr-labeler'

on:
  - pull_request_target

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/labeler
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
