---
name: '!gh-release-publisher'

on:
  release:
    types: ['published']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Change collection version to match tag
        run: |
          sed -Ei "s/^version: .*/version: ${{ env.GIT_TAG }}/" galaxy.yml
      - run: python -m pip install ansible-core
      - run: ansible-galaxy collection build --verbose
      - run: ansible-galaxy collection publish --token ${{ secrets.GALAXY_TOKEN }} bonddim-linux-${{ env.GIT_TAG }}.tar.gz
