---
name: molecule

on:
  workflow_call:
    inputs:
      scenario:
        required: true
        type: string

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Set build matrix
        id: set-matrix
        uses: bonddim/action-workflow-matrix@stable
        with:
          workflow: ${{ inputs.scenario }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: matrix
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: bonddim/action-lxd-init@stable
      - name: Install tox
        run: python -m pip install tox
      - name: Run tox -e ${{ matrix.tox_env }}
        run: tox -- --scenario-name ${{ inputs.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          INSTALL_METHOD: ${{ matrix.install_method }}
