---
name: users

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  pull_request:
    paths:
      - 'roles/users/**'
      - 'molecule/users/**'
      - '.github/workflows/role_users.yaml'

jobs:
  molecule:
    uses: ./.github/workflows/molecule.yaml
    with:
      scenario: ${{ github.workflow }}
