---
name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  push:
    paths:
      - 'roles/docker/**'
      - 'molecule/docker/**'
      - '.github/workflows/role_docker.yaml'
  pull_request:
    paths:
      - 'roles/docker/**'
      - 'molecule/docker/**'
      - '.github/workflows/role_docker.yaml'

jobs:
  molecule:
    # skip job on pull requests from base repository and tag push
    if: (github.event.pull_request.head.repo.full_name != github.repository) && !startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/molecule.yaml
    with:
      scenario: ${{ github.workflow }}
