---
name: traefik

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  pull_request:
    paths:
      - 'roles/traefik/**'
      - 'molecule/traefik/**'
      - '.github/workflows/role_traefik.yaml'

jobs:
  molecule:
    uses: ./.github/workflows/molecule.yaml
    with:
      scenario: ${{ github.workflow }}
