---
name: lxd

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  pull_request:
    paths:
      - 'roles/lxd/**'
      - 'molecule/lxd/**'
      - '.github/workflows/role_lxd.yaml'

jobs:
  molecule:
    uses: ./.github/workflows/molecule.yaml
    with:
      scenario: ${{ github.workflow }}
