---
name: Molecule

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  molecule:
    name: Test on ${{ matrix.distro }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: bonddim.users
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu/20.04
          - ubuntu/18.04
          - debian/10
          - debian/9
          - fedora/32
          - fedora/31
          - centos/8
          - centos/7

    steps:
      - uses: actions/checkout@v2
        with:
          path: bonddim.users
      - uses: bonddim/action-lxd-init@stable
      - name: Install dependencies
        run: sudo python3 -m pip install ansible-lint yamllint molecule-lxd
      - run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: true