---
name: epel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  pull_request:
    paths:
      - 'roles/epel/**'
      - 'molecule/epel/**'
      - '.github/workflows/role_epel.yaml'

jobs:
  molecule:
    uses: ./.github/workflows/molecule.yaml
    with:
      scenario: ${{ github.workflow }}
