---
name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  pull_request:
    paths:
      - 'roles/docker/**'
      - 'molecule/docker/**'
      - '.github/workflows/role_docker.yaml'

jobs:
  molecule:
    uses: ./.github/workflows/molecule.yaml
    with:
      scenario: ${{ github.workflow }}
